
name: Automatisation des tests DevSecOps

on:
  push:
  pull_request:

jobs:
  Dependances:
    runs-on: ubuntu-latest

    steps:
      - name: Recuperer le repository
        uses: actions/checkout@v4

      - name: Installer Trivy
        uses: aquasecurity/setup-trivy@v0.2.3

      - name: Scanner les dependances Python
        run: |
          trivy fs \
            --scanners vuln \
            --include-dev-deps \
            --severity HIGH,CRITICAL \
            --exit-code 1 \
            --format table \
            .

  Dockerfile:
    runs-on: ubuntu-latest
    needs: Dependances

    steps:
      - name: Recuperer le repository
        uses: actions/checkout@v4

      - name: Installer Trivy
        uses: aquasecurity/setup-trivy@v0.2.3

      - name: Scanner le Dockerfile
        run: |
          trivy config \
            --severity HIGH,CRITICAL \
            --exit-code 1 \
            --format table \
            Dockerfile

  Deploy:
    runs-on: ubuntu-latest
    needs: Dockerfile

    steps:
      - name: Deploy
        run: |
          echo "Les controles de securite sont valides."
          echo "L'application est prete a etre deployee."
